name: 'publish'

on:
  push:
    branches:
      - release

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  ffmpeg:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            ffmpeg-link: 'https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1.1-full_build.7z'
            ffmpeg-name: 'ffmpeg-7.1.1-full_build'
          - platform: ubuntu-22.04
            ffmpeg-link: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-08-31-13-00/ffmpeg-n7.1.1-57-g1b48158a23-linux64-gpl-7.1.tar.xz
            ffmpeg-name: 'ffmpeg-n7.1.1-57-g1b48158a23-linux64-gpl-7.1'
    
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: create src-tauri/binaries folder
        run: mkdir src-tauri/binaries

      - name: install ffmpeg (windows)
        if: matrix.platform == 'windows-latest'
        run: Invoke-WebRequest https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1.1-full_build.7z -OutFile ffmpeg.7z
      
      - name: extract ffmpeg (windows)
        if: matrix.platform == 'windows-latest'
        run: 7z x ffmpeg.7z

      - name: move ffmpeg to binaries folder (windows)
        if: matrix.platform == 'windows-latest'
        run: mv ffmpeg-7.1.1-full_build/bin/ffmpeg.exe src-tauri/binaries/ffmpeg-x86_64-pc-windows-msvc.exe

      - name: install ffmpeg (linux)
        if: matrix.platform == 'ubuntu-22.04'
        run:
          wget -O ffmpeg.tar.xz ${{ matrix.ffmpeg-link }}

      - name: extract ffmpeg (linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: tar -xf ffmpeg.tar.xz ${{ matrix.ffmpeg-name }}/bin

      - name: move ffmpeg to binaries folder (linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: mv ${{ matrix.ffmpeg-name }}/bin/ffmpeg src-tauri/binaries

  publish-tauri:
    needs:
      ffmpeg
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ''
          - platform: ubuntu-22.04
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.

      - name: install frontend dependencies
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: '__VERSION__'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  # publish-tauri:
  #   permissions:
  #     contents: write
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - platform: 'windows-latest'
  #           args: ''
  #           ffmpeg-link: 'https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1.1-full_build.7z'
  #         - platform: 'ubuntu-22.04'
  #           args: ''
  #           ffmpeg-link: 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-08-31-13-00/ffmpeg-n7.1.1-57-g1b48158a23-linux64-gpl-7.1.tar.xz'

  #   runs-on: ${{ matrix.platform }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: install ffmpeg
  #       run: Invoke-WebRequest https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1.1-full_build.7z -OutFile ffmpeg.7z
      
  #     - name: unzip ffmpeg
  #       run: 7z x ffmpeg.7z

  #     - name: move ffmpeg to binaries folder
  #       run: |
  #         mkdir src-tauri/binaries
  #         mv ffmpeg-7.1.1-full_build/bin/ffmpeg.exe src-tauri/binaries/ffmpeg-x86_64-pc-windows-msvc.exe

  #     - name: setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*

  #     - name: install Rust stable
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
  #         targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

  #     - name: install dependencies (ubuntu only)
  #       if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
  #       # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
  #       # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

  #     - name: install frontend dependencies
  #       run: npm install # change this to npm, pnpm or bun depending on which one you use.

  #     - uses: tauri-apps/tauri-action@v0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  #         TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
  #       with:
  #         tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
  #         releaseName: '__VERSION__'
  #         releaseDraft: true
  #         prerelease: false
  #         args: ${{ matrix.args }}
